- src/index.ts
- src/pug-token.ts
- test/issues/issue-11/formatted.pug
- test/issues/issue-11/issue-11.test.ts
- test/issues/issue-11/unformatted.pug
- test/mixins/formatted.pug
- test/mixins/mixins.test.ts
- test/mixins/unformatted.pug
> Add support for mixins

- src/index.ts
- test/issues/issue-9/formatted.pug
- test/issues/issue-9/issue-9.test.ts
- test/issues/issue-9/unformatted.pug
> Escape quotes correctly

- CHANGELOG.md
- src/index.ts
- src/options.ts
- test/options/attributeSeparator/always/always.test.ts
- test/options/attributeSeparator/always/formatted.pug
- test/options/attributeSeparator/always/unformatted.pug
- test/options/attributeSeparator/as-needed/as-needed.test.ts
- test/options/attributeSeparator/as-needed/formatted.pug
- test/options/attributeSeparator/as-needed/unformatted.pug
> Introduce new option attributeSeparator

- src/index.ts
- test/issues/issue-18/formatted.pug
- test/issues/issue-18/issue-18.test.ts
- test/issues/issue-18/unformatted.pug
> Fix indent for include

- src/doctype-shortcut-registry.ts
- src/index.ts
- src/pug-token.ts
- test/issues/issue-24/formatted.pug
- test/issues/issue-24/issue-24.test.ts
- test/issues/issue-24/unformatted.pug
- test/text-html/formatted.pug
- test/text-html/text-html.test.ts
- test/text-html/unformatted.pug
> Support text-html token

- src/index.ts
- test/issues/issue-27/formatted.pug
- test/issues/issue-27/issue-27.test.ts
- test/issues/issue-27/unformatted.pug
> Fix interpolated issue

- src/index.ts
- src/pug-token.ts
- test/issues/issue-29/formatted.pug
- test/issues/issue-29/issue-29.test.ts
- test/issues/issue-29/unformatted.pug
> Support each token

- src/index.ts
- test/issues/issue-31/formatted.pug
- test/issues/issue-31/issue-31.test.ts
- test/issues/issue-31/unformatted.pug
> Handle mustEscape for buffered code token

- src/index.ts
- src/pug-token.ts
- test/issues/issue-34/formatted.pug
- test/issues/issue-34/issue-34.test.ts
- test/issues/issue-34/unformatted.pug
> Support while and case

- src/index.ts
- src/pug-token.ts
- test/issues/issue-38/formatted.pug
- test/issues/issue-38/issue-38.test.ts
- test/issues/issue-38/unformatted.pug
> Add support for else-if

- src/index.ts
- src/pug-token.ts
- test/issues/issue-40/formatted.pug
- test/issues/issue-40/issue-40.test.ts
- test/issues/issue-40/unformatted.pug
> Add support for interpolation

- src/index.ts
- src/pug-token.ts
- test/issues/issue-39/formatted.pug
- test/issues/issue-39/issue-39.test.ts
- test/issues/issue-39/unformatted.pug
> Add support for blockcode

- README.md
- package.json
- src/index.ts
- src/options.ts
- test/comments/comments.test.ts
- test/options/commentPreserveSpaces/keep-all/formatted.pug
- test/options/commentPreserveSpaces/keep-all/keep-all.test.ts
- test/options/commentPreserveSpaces/keep-all/unformatted.pug
- test/options/commentPreserveSpaces/keep-leading/formatted.pug
- test/options/commentPreserveSpaces/keep-leading/keep-leading.test.ts
- test/options/commentPreserveSpaces/keep-leading/unformatted.pug
- test/options/commentPreserveSpaces/trim-all/formatted.pug
- test/options/commentPreserveSpaces/trim-all/trim-all.test.ts
- test/options/commentPreserveSpaces/trim-all/unformatted.pug
> Formatting of comments

- src/index.ts
- test/issues/issue-49/formatted.pug
- test/issues/issue-49/issue-49.test.ts
- test/issues/issue-49/unformatted.pug
> Handle interpolation following an id

- src/index.ts
- test/issues/issue-51/formatted.pug
- test/issues/issue-51/issue-51.test.ts
- test/issues/issue-51/unformatted.pug
> Transform only valid id attributes

- src/index.ts
- test/issues/issue-52/formatted.pug
- test/issues/issue-52/issue-52.test.ts
- test/issues/issue-52/unformatted.pug
> Handle literal line

- .eslintrc.json
- src/index.ts
- test/issues/issue-61/formatted.pug
- test/issues/issue-61/issue-61.test.ts
- test/issues/issue-61/unformatted.pug
> No wrapping for chained data bindings

- .gitignore
- src/index.ts
- test/issues/issue-63/formatted.pug
- test/issues/issue-63/issue-63.test.ts
- test/issues/issue-63/unformatted.pug
- test/pug-tests/block-expansion.shorthands.formatted.pug
- test/pug-tests/block-expansion.shorthands.pug
- test/pug-tests/mixin.attrs.formatted.pug
- test/pug-tests/mixin.attrs.pug
> Handle ID behind attribute with dot

- src/printer.ts
- src/utils/angular.ts
- src/utils/common.ts
- test/issues/issue-67/formatted.pug
- test/issues/issue-67/issue-67.test.ts
- test/issues/issue-67/unformatted.pug
> Distinguish between angular binding and action

- src/printer.ts
- src/utils/common.ts
- test/issues/issue-70/formatted.pug
- test/issues/issue-70/issue-70.test.ts
- test/issues/issue-70/unformatted.pug
- test/issues/issue-9/unformatted.pug
> Handle interpolation

- src/printer.ts
- test/spaces/formatted.pug
- test/spaces/unformatted.pug
> Handle space for indented text

- src/printer.ts
- test/issues/issue-89/formatted.pug
- test/issues/issue-89/issue-89.test.ts
- test/issues/issue-89/unformatted.pug
closes #89 
closes #90
closes #91
closes #92
> Fix indention in multi-line blank lines

- src/printer.ts
- test/issues/issue-95/formatted.pug
- test/issues/issue-95/issue-95.test.ts
- test/issues/issue-95/unformatted.pug
> Issue 95; Properly order class/id with "hidden" div

- README.md
- src/index.ts
- src/printer.ts
- test/options/bracketSpacing/bracket-spacing.test.ts
- test/options/bracketSpacing/formatted.pug
- test/options/bracketSpacing/unformatted.pug
> Support bracketSpacing option (only text-token)

- src/printer.ts
- src/utils/common.ts
- tests/options/bracketSpacing/formatted.pug
- tests/options/bracketSpacing/unformatted.pug
> Support bracketSpacing option for attributes

- tests/issues/issue-107/formatted.pug
- tests/issues/issue-107/issue-107.test.ts
- tests/issues/issue-107/unformatted.pug
> Fix pug in brackets turned into multi line

- src/printer.ts
- tests/issues/issue-110/formatted.pug
- tests/issues/issue-110/issue-110.test.ts
- tests/issues/issue-110/unformatted.pug
> Fix indentation of objects in multiline class attributes

- README.md
As discussed here: https://github.com/prettier/plugin-pug/issues/118#issuecomment-700724677
> Update README to mention all pug alias options

- README.md
- src/options/converge.ts
- src/options/index.ts
- src/options/wrap-attributes.ts
- src/printer.ts
- tests/options/pugWrapAttributesPattern/formatted.pug
- tests/options/pugWrapAttributesPattern/unformatted.pug
- tests/options/pugWrapAttributesPattern/wrap-attributes-pattern.test.ts
> Implement pugWrapAttributesPattern option

- src/printer.ts
- tests/literals/id-class-literals/formatted.pug
- tests/literals/id-class-literals/id-class-literals.test.ts
- tests/literals/id-class-literals/unformatted.pug
- tests/options/pugWrapAttributesThreshold/0/formatted.pug
- tests/options/pugWrapAttributesThreshold/0/unformatted.pug
- tests/options/pugWrapAttributesThreshold/1/formatted.pug
- tests/options/pugWrapAttributesThreshold/1/unformatted.pug
- tests/options/pugWrapAttributesThreshold/2/formatted.pug
- tests/options/pugWrapAttributesThreshold/2/unformatted.pug
- tests/options/pugWrapAttributesThreshold/default/formatted.pug
- tests/options/pugWrapAttributesThreshold/default/unformatted.pug
This PR fixes issue #130.
But for all the test to pass, #121 needs to be merged first.
> Fix handling of combined literal attributes

- package.json
- src/printer.ts
- tests/plain-text/formatted.pug
- tests/plain-text/plain-text.test.ts
- tests/plain-text/unformatted.pug
- yarn.lock
> Handle plain-text tokens after outdent

- src/printer.ts
- tests/plain-text/formatted.pug
- tests/plain-text/unformatted.pug
> Fix issues with plain-text and nesting (#138)

- src/index.ts
> Add pug to vscodeLanguageIds

- src/printer.ts
- tests/issues/issue-148/formatted.vue
- tests/issues/issue-148/issue-148.test.ts
- tests/issues/issue-148/unformatted.vue
> Fix bracket interpolation in combination with pugSingleFileComponentIndentation

- src/printer.ts
- tests/issues/issue-149/formatted.pug
- tests/issues/issue-149/issue-149.test.ts
- tests/issues/issue-149/unformatted.pug
> Do not wrap attributes in enclosed code interpolation

- src/printer.ts
- tests/issues/issue-147/formatted.pug
- tests/issues/issue-147/issue-147.test.ts
- tests/issues/issue-147/unformatted.pug
> Print warning for parsed object shorthand notation

- .gitignore
- src/printer.ts
- src/utils/common.ts
- tests/issues/issue-158/formatted.pug
- tests/issues/issue-158/issue-158.test.ts
- tests/issues/issue-158/unformatted.pug
- tests/pug-tests/pug.test.ts
- tests/pug-tests/script.whitespace.formatted.pug
- tests/pug-tests/script.whitespace.pug
- tests/pug-tests/styles.formatted.pug
- tests/pug-tests/styles.pug
> Format inline scripts and styles

- src/printer.ts
- tests/issues/issue-169/formatted.pug
- tests/issues/issue-169/issue-169.test.ts
- tests/issues/issue-169/unformatted.pug
- tests/syntax-errors/pipeless-script-tag.pug
- tests/syntax-errors/syntax-errors.test.ts
> Handle error thrown by interpolated code in pipeless script tag

- src/printer.ts
- src/utils/vue.ts
- tests/issues/issue-176/formatted.pug
- tests/issues/issue-176/issue-176.test.ts
- tests/issues/issue-176/unformatted.pug
> Handle v-on expression separately

- src/utils/vue.ts
- tests/issues/issue-180/formatted.pug
- tests/issues/issue-180/issue-180.test.ts
- tests/issues/issue-180/unformatted.pug
> Handle v-slot expression correctly

- docs/guide/pug-specific-options.md
- src/options/pug-framework.ts
- src/printer.ts
- src/utils/common.ts
- tests/frameworks/detection.test.ts
> Rename pugFramework default to auto

- CHANGELOG.md
- src/printer.ts
- tests/issues/issue-206/formatted.pug
- tests/issues/issue-206/issue-206.test.ts
- tests/issues/issue-206/unformatted.pug
> Fix invalid added semicolon in front of template string

- src/options/attribute-sorting/utils.ts
- tests/issues/issue-192/formatted.pug
- tests/issues/issue-192/issue-192.test.ts
- tests/issues/issue-192/unformatted.pug
> Optimize sorting algorithm functions

- src/printer.ts
- tests/issues/issue-255/formatted.pug
- tests/issues/issue-255/issue-255.test.ts
- tests/issues/issue-255/unformatted.pug
> Prevent wrong quotation

- .vscode/settings.json
- src/printer.ts
- src/utils/common.ts
- tests/issues/issue-261/formatted.pug
- tests/issues/issue-261/issue-261.test.ts
- tests/issues/issue-261/unformatted.pug
> Preserve backticks for class and id attributes

- src/printer.ts
- tests/issues/issue-268/formatted.pug
- tests/issues/issue-268/issue-268.test.ts
- tests/issues/issue-268/unformatted.pug
> Use pugTabWidth for calculating line length

- src/printer.ts
- tests/issues/issue-278/formatted.pug
- tests/issues/issue-278/issue-278.test.ts
- tests/issues/issue-278/unformatted.pug
> Fix trailing indentations after pipeless text

- src/printer.ts
- tests/issues/issue-282/class-indented.vue
- tests/issues/issue-282/class-not-indented.vue
- tests/issues/issue-282/id-indented.vue
- tests/issues/issue-282/id-not-indented.vue
- tests/issues/issue-282/issue-282.test.ts
> Fix indentation of templates starting with class or ID when using pugSingleFileComponentIndentation

- src/utils/vue.ts
- tests/issues/issue-289/formatted.pug
- tests/issues/issue-289/formatted.vue
- tests/issues/issue-289/issue-289.test.ts
- tests/issues/issue-289/unformatted.pug
- tests/issues/issue-289/unformatted.vue
> Handle Vue slot shorthand syntax

- src/printer.ts
- tests/issues/issue-292/formatted.pug
- tests/issues/issue-292/issue-292.test.ts
- tests/issues/issue-292/unformatted.pug
> Fix handling of prettier-ignore

- docs/.vuepress/config.js
> Fix "Edit this page" link

- src/printer.ts
- tests/issues/issue-307/formatted.pug
- tests/issues/issue-307/issue-307.test.ts
- tests/issues/issue-307/unformatted.pug
>  Fix indentation issue of inline javascript

- src/utils/vue.ts
- tests/issues/issue-310/formatted.pug
- tests/issues/issue-310/issue-310.test.ts
- tests/issues/issue-310/unformatted.pug
> Treat `v-t` from vue-i18n as Vue expression

- docs/guide/pug-specific-options.md
- src/options/converge.ts
- src/options/index.ts
- src/options/pug-class-location.ts
- src/prettier.d.ts
- src/printer.ts
- tests/options/pugClassLocation/formatted-after.pug
- tests/options/pugClassLocation/formatted-before.pug
- tests/options/pugClassLocation/pug-class-location.test.ts
- tests/options/pugClassLocation/unformatted.pug
> Add `pugClassLocation` option

- src/printer.ts
- tests/issues/issue-317/formatted.pug
- tests/issues/issue-317/issue-317.test.ts
- tests/issues/issue-317/unformatted.pug
> Fix instable `pugClassNotation` with `printWidth`

- src/printer.ts
- tests/options/pugClassLocation/formatted-after.pug
- tests/options/pugClassLocation/formatted-before.pug
- tests/options/pugClassLocation/unformatted.pug
> Handle colon token in combination with `pugClassLocation: 'after-attributes'`

- src/printer.ts
- tests/issues/issue-329/formatted.pug
- tests/issues/issue-329/issue-329.test.ts
- tests/issues/issue-329/unformatted.pug
> Handle nested Angular translations

- src/printer.ts
- tests/issues/issue-402/formatted.pug
- tests/issues/issue-402/issue-402.test.ts
- tests/issues/issue-402/unformatted.pug
> Preserve script tag after `//- prettier-ignore`

- docs/guide/pug-specific-options.md
- src/options/converge.ts
- src/options/index.ts
- src/options/pug-preserve-attribute-brackets.ts
- src/options/types.ts
- src/prettier.d.ts
- src/printer.ts
- tests/options/pugPreserveAttributeBrackets/formatted-false.pug
- tests/options/pugPreserveAttributeBrackets/formatted-true.pug
- tests/options/pugPreserveAttributeBrackets/pug-preserve-attribute-brackets.test.ts
- tests/options/pugPreserveAttributeBrackets/unformatted.pug
> Add `pugPreserveAttributeBrackets` option

- src/printer.ts
- tests/options/semi/none-none/formatted.pug
- tests/options/semi/none-none/unformatted.pug
- tests/options/semi/none-semi/formatted.pug
- tests/options/semi/none-semi/unformatted.pug
- tests/options/semi/semi-none/formatted.pug
- tests/options/semi/semi-none/unformatted.pug
- tests/options/semi/semi-semi/formatted.pug
- tests/options/semi/semi-semi/unformatted.pug
- tests/options/semi/semi.test.ts
Simple tests that are complementary to #423
> Add semi code interpolation option

- src/printer.ts
- tests/issues/issue-425/formatted.pug
- tests/issues/issue-425/issue-425.test.ts
- tests/issues/issue-425/unformatted.pug
> Fix trailing whitespace after tag

- src/printer.ts
- tests/issues/issue-428/formatted.pug
- tests/issues/issue-428/issue-428.test.ts
- tests/issues/issue-428/unformatted.pug
> Omit leading semicolon in code expressions

- .github/workflows/ci.yml
- package.json
Node v14 reached EOL 2023-04-30
> Drop NodeJS v14 support

- src/printer.ts
- tests/issues/issue-447/formatted.pug
- tests/issues/issue-447/issue-447.test.ts
- tests/issues/issue-447/unformatted.pug
> Handle whitespace in interpolations
