.eslintrc.json, .vscode/settings.json, package.json, src/index.ts, src/logger.ts, yarn.lock
=> Setup eslint with TypeScript configuration

src/index.ts, src/pug-token.ts, test/indents/formatted-2-spaces.pug, test/indents/formatted-3-spaces.pug, test/indents/formatted-4-spaces.pug, test/indents/formatted-tabs.pug, test/literals/class-literals/formatted.pug, test/literals/class-literals/unformatted.pug, test/literals/id-literals/formatted.pug, test/literals/id-literals/unformatted.pug, test/quotes/double-to-single/formatted.pug, test/quotes/single-to-double/formatted.pug
=> Support wrap attributes

src/printer.ts, test/options/closingBracketPosition/last-line/formatted.pug, test/options/closingBracketPosition/last-line/unformatted.pug
- Each nesting was adding an empty space while `closingBracketPosition` equals to `last-line`
-  An improved test added.
- #82
=> Bugfix: nested closed brackets was causing a dash bug

src/printer.ts, test/issues/issue-85/formatted.pug, test/issues/issue-85/issue-85.test.ts, test/issues/issue-85/unformatted.pug
=> Fix semi in code interpolation

src/printer.ts, src/utils/common.ts, test/issues/issue-80/formatted.pug, test/issues/issue-80/issue-80.test.ts, test/issues/issue-80/unformatted.pug
Object literals are widely used in Vue.
For example, they can be used to assign set of classes conditionally:
```pug
span.aui-lozenge(
:class=`{
"aui-lozenge-inprogress": pipeline.status == PipelineStatus.Running,
"aui-lozenge-error":      pipeline.status == PipelineStatus.Failed
}`
)
```
This patch does not modify behavior regarding non-multiline strings.
Fixes #80.
=> Do not reformat interpolation attribute values

CHANGELOG.md, README.md, src/index.ts, src/options/attribute-separator.ts, src/options/closing-bracket-position.ts, src/options/comment-preserve-spaces.ts, src/options/common.ts, src/options/converge.ts, src/options/index.ts, src/printer.ts, tests/issues/issue-105/formatted.vue, tests/issues/issue-105/issue-105.test.ts, tests/issues/issue-105/unformatted.vue, tests/options/attributeSeparator/always/always.test.ts, tests/options/attributeSeparator/as-needed/as-needed.test.ts, tests/options/singleQuote/single-quote.test.ts
=> Add pug aliased options

package.json, src/options/attribute-sorting/index.ts, src/options/attribute-sorting/utils.ts, src/options/converge.ts, src/options/index.ts, src/printer.ts, tests/options/sortAttributes/formatted.pug, tests/options/sortAttributes/sort-attributes.test.ts, tests/options/sortAttributes/unformatted.pug
<details>
Every time this code is saved it gets a different result:
```vue
<template lang="pug">
Foo(c b a d i f g h e l n)
</template>
```
```vue
<template lang="pug">
Foo(a b c d e f g h i l n)
</template>
```
<details>
=> Add middle attributes sorting

README.md, src/printer.ts, tests/options/attributeSeparator/always/always.test.ts, tests/options/attributeSeparator/always/formatted.pug, tests/options/attributeSeparator/always/unformatted.pug, tests/options/attributeSeparator/as-needed/as-needed.test.ts, tests/options/attributeSeparator/as-needed/formatted.pug, tests/options/attributeSeparator/as-needed/unformatted.pug, tests/options/attributeSeparator/none/formatted.pug, tests/options/attributeSeparator/none/none.test.ts, tests/options/attributeSeparator/none/unformatted.pug
I noticed that the current line-length wasn't counted correctly depending on the setting of attributeSeparator.  
This PR fixes that and adds tests for the various settings.
=> Fix counting of current line-length

.editorconfig, README.md, src/index.ts, src/printer.ts, tests/prettier-ignore/formatted.pug, tests/prettier-ignore/prettier-ignore.test.ts, tests/prettier-ignore/unformatted.pug
Use `//- prettier-ignore` comments to prevent automatic formatting of the following line or block:
```pug
div
.wrapper-1(attributes1="foo", :attribute2="bar", attribute3="something too long to keep on one line")
//- prettier-ignore
.wrapper-2(attributes1="foo", :attribute2="bar", attribute3="something too long to keep on one line")
.wrapper-3(attributes1="foo", :attribute2="bar", attribute3="something too long to keep on one line")
//- prettier-ignore
div
.wrapper-4(attributes1="foo", :attribute2="bar", attribute3="something too long to keep on one line")
.wrapper-5(attributes1="foo", :attribute2="bar", attribute3="something too long to keep on one line")
```
->
```pug
div
.wrapper-1(
attributes1="foo",
:attribute2="bar",
attribute3="something too long to keep on one line"
)
//- …
```
=> Support prettier-ignore comments inside pug templates

src/printer.ts, tests/literals/matching-content/formatted.pug, tests/literals/matching-content/matching-content.test.ts, tests/literals/matching-content/unformatted.pug
=> Improve conversion of tags to literals

tests/issues/issue-156/formatted.pug, tests/issues/issue-156/issue-156.test.ts, tests/issues/issue-156/unformatted.pug
=> Handle multiline inline script

README.md, src/utils/common.ts, tests/issues/issue-58/formatted.pug, tests/issues/issue-58/issue-58.test.ts, tests/issues/issue-58/unformatted.pug
=> Fix attribute interpolation using quotes

docs/guide/pug-specific-options.md, src/options/pug-class-notation.ts, src/printer.ts, tests/options/pugClassNotation/formatted-attribute.pug, tests/options/pugClassNotation/formatted-literal.pug, tests/options/pugClassNotation/pug-class-notation.test.ts, tests/options/pugClassNotation/unformatted.pug
This is a partial fix for #167 covering classes, I think it _should_ be fairly straightforward to implement for IDs next, please let me know if this direction is right and I'll get on to it!
Thanks!
=> Add pugClassNotation 'attribute' option

.eslintrc.js, .vscode/settings.json, src/printer.ts, src/utils/common.ts, src/utils/script-mime-types.ts, tests/syntax-errors/scripts-with-non-js-contents.pug, tests/syntax-errors/syntax-errors.test.ts
@Shinigami92 I ended up doing most this before you PR'd. Take what you like from it or close it.
To add the I collated all the current IANA types in a single file: [media-types.txt](https://github.com/prettier/plugin-pug/files/6759064/media-types.txt) from the official [IANA reference](https://www.iana.org/assignments/media-types/media-types.xhtml). But most of them are not textual so have nothing to do with `<script>` tags. I've tried to find some sort of reference collating what people use the `type` attribute. Apart from refs to the old `language` attribute and VBScript, JScript and TCL and these aren't worth supporting.
=> Handle non-JS script content

src/printer.ts, src/utils/common.ts, tests/issues/issue-250/formatted.pug, tests/issues/issue-250/issue-250.test.ts, tests/issues/issue-250/unformatted.pug, tests/issues/issue-61/formatted.pug, tests/issues/issue-61/unformatted.pug, tests/issues/issue-80/formatted.pug, tests/issues/issue-80/unformatted.pug
- First commit adds a unit test to expose issue #250.
- Second commit changes code so that new test passes and all other test still pass (checks for quotes before stripping them).
Note that I changed `isQuoted` and added the back-tic quote to the test with the other two quote styles (was `"'`, now is ``"`'``). All the tests pass, running this on my code based produced correct results, but I only have plain and Vue-based code (no angular, react, svelte, etc..).  I looked at all the calling sites of `isQuoted` and it looks okay to me, but someone more familiar with the code base should probably review that carefully.
=> Fix corrupt attribute values on dynamically bound Vue props without quotes

.vscode/launch.json, jest.config.js
This change allows you to debug in and step through live code when testing
=> Add `.vscode/launch.json` for debugging

pnpm-lock.yaml, src/printer.ts, tests/issues/issue-339/double-quotes.pug, tests/issues/issue-339/issue-339.test.ts, tests/issues/issue-339/single-quotes.pug
=> Fix single quotes in framework interpolation

src/printer.ts, tests/issues/issue-405/formatted.vue, tests/issues/issue-405/issue-405.test.ts, tests/issues/issue-405/unformatted.vue
=> Fix indent with pugExplicitDiv and pugClassNotation=attribute

src/printer.ts, tests/issues/issue-439/formatted.pug, tests/issues/issue-439/issue-439.test.ts, tests/issues/issue-439/unformatted.pug
=> Fix trailing whitespace after class

README.md, docs/guide/index.md
Just to avoid #463 occurring again, here's a change to README.md to reflect the latest version's usage changes.
=> Enhance Documentation

src/printer.ts, tests/options/pugWrapAttributesThreshold/withAsIsClassNotation/formatted.pug, tests/options/pugWrapAttributesThreshold/withAsIsClassNotation/unformatted.pug, tests/options/pugWrapAttributesThreshold/withAsIsClassNotation/with-as-is-class-notation.test.ts, tests/options/pugWrapAttributesThreshold/withAsIsIdNotation/formatted.pug, tests/options/pugWrapAttributesThreshold/withAsIsIdNotation/unformatted.pug, tests/options/pugWrapAttributesThreshold/withAsIsIdNotation/with-as-is-id-notation.test.ts, tests/options/pugWrapAttributesThreshold/withAttributeClassNotation/formatted.pug, tests/options/pugWrapAttributesThreshold/withAttributeClassNotation/unformatted.pug, tests/options/pugWrapAttributesThreshold/withAttributeClassNotation/with-attribute-class-notation.test.ts
There are a few issues with the `pugClassNotation: 'attribute'` option that resolve themselves with multiple repeated runs (one run to convert from literals to attributes with broken formatting, another run to fix the formatting) but one issue persists.
Classes are not counted to `numNormalAttributes` when deciding if the attributes should be wrapped as per `pugWrapAttributesThreshold`. This causes lines not to wrap as expected if they have class attributes.
Input with `pugWrapAttributesThreshold: 1` and `pugClassNotation: 'attribute'`:
```pug
div(class="class" attribute="value")
```
Output:
```pug
// Still on one line (bad)
div(class="class" attribute="value")
```
Expected output:
```pug
div(
class="class",
attribute="value"
)
```
I added an extra check to the code path for classes that …
=> Fix class attributes not counting towards attribute wrapping

src/printer.ts, tests/options/pugClassNotation/formatted-as-is.pug, tests/options/pugClassNotation/formatted-attribute.pug, tests/options/pugClassNotation/formatted-literal.pug, tests/options/pugClassNotation/pug-class-notation.test.ts, tests/options/pugClassNotation/unformatted.pug
Closes #508 
This PR adds tests and fixes for previously untested variations of class literals in increasingly complex scenarios. Most of them output non-valid Pug code currently.
I fixed all the new test cases to output valid Pug code without regressions, so this is probably safe to merge. I don't have full confidence that there are no other (currently untested) bad combinations of the various options, but this is for sure better than before.
Examples of code that previously outputted invalid Pug but now work:
```pug
// Class literals at the end of attributes did not work.
div(attribute="value").foo
div(class="bar", attribute="value").foo
div(attribute="value", class="bar").foo.baz
div(
attribute="value"
class="bar"
).foo.baz
div.foo(attribute="value" class="bar").baz
// Class literals …
```
=> Multiple fixes for class attribute conversions

src/printer.ts, tests/issues/issue-365/formatted.vue, tests/issues/issue-365/issue-365.test.ts, tests/issues/issue-365/unformatted.vue
closes #365
depends on prettier release of https://github.com/prettier/prettier/pull/12584
=> Handle vue ts
